# Generated by Django 5.2.8 on 2025-11-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_basico',
            field=models.BooleanField(default=True, help_text='¿Es un producto de necesidad básica?'),
        ),
    ]
