# Generated by Django 5.2.8 on 2025-11-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_es_basico'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='general', help_text='Categoría del producto (por ejemplo: alimentos, bebidas, aseo, dulces, ferretería, etc.)', max_length=50),
        ),
    ]
